name: benchmark

on:
  pull_request_target:
    branches: [ master ]

jobs:
  benchmark_base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        cache: 'pip' # cache for faster build
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e .
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install benchmark package
      run: |
        pip install -r requirements_benchmark.txt
    - name: Benchmark test
      run: |
        python cvxpy/benchmarks/run_benchmarks.py
    - name: Render benchmark_report.md
      id: benchmark_head
      uses: chuhlomin/render-template@v1.4
      with:
        template: cvxpy/benchmarks/benchmark_report.md
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.benchmark_head.outputs.result }}

    # Ref
    - name: Get latest release
      id: get_release
      run: |
          echo "REF=$(git describe --tags --abbrev=0 --match v[1-9]* $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.REF }}
    - name: Benchmark test
      run: |
        python cvxpy/benchmarks/run_benchmarks.py
    - name: Render benchmark_report.md
      id: benchmark_ref
      uses: chuhlomin/render-template@v1.4
      with:
        template: cvxpy/benchmarks/benchmark_report.md
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.benchmark_ref.outputs.result }}
